//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroatianLessons.Standard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CroatianLessons.Standard.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AnswerNo {
            get {
                return ResourceManager.GetString("AnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AnswerYes {
            get {
                return ResourceManager.GetString("AnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian Lessons For Tourists.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close ✕.
        /// </summary>
        internal static string BtnCloseLesson {
            get {
                return ResourceManager.GetString("BtnCloseLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string BtnFinish {
            get {
                return ResourceManager.GetString("BtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next lesson ».
        /// </summary>
        internal static string BtnNextLesson {
            get {
                return ResourceManager.GetString("BtnNextLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Previous lesson.
        /// </summary>
        internal static string BtnPrevLesson {
            get {
                return ResourceManager.GetString("BtnPrevLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start!.
        /// </summary>
        internal static string BtnStartLearning {
            get {
                return ResourceManager.GetString("BtnStartLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Love Carpe Diem&apos;s Croatian Lessons!.
        /// </summary>
        internal static string IntroInfoMsg {
            get {
                return ResourceManager.GetString("IntroInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device&apos;s language is .
        /// </summary>
        internal static string IntroLanguageInfo {
            get {
                return ResourceManager.GetString("IntroLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application language:.
        /// </summary>
        internal static string LabelSelectLanguage {
            get {
                return ResourceManager.GetString("LabelSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change language to xxxx.
        /// </summary>
        internal static string LanguageChangeDialogText {
            get {
                return ResourceManager.GetString("LanguageChangeDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Change.
        /// </summary>
        internal static string LanguageChangeDialogTitle {
            get {
                return ResourceManager.GetString("LanguageChangeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is set to your device&apos;s language. You can change the language here or later in Settings.
        /// </summary>
        internal static string LanguageFoundInfo {
            get {
                return ResourceManager.GetString("LanguageFoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is set to your device&apos;s language. You can change the language here..
        /// </summary>
        internal static string LanguageFoundInfoSettings {
            get {
                return ResourceManager.GetString("LanguageFoundInfoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your language is not supported in this version. Use default English language or pick another language here now or later in Settings..
        /// </summary>
        internal static string LanguageNotFoundInfo {
            get {
                return ResourceManager.GetString("LanguageNotFoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your language is not supported in this version. Use default English language or pick another language..
        /// </summary>
        internal static string LanguageNotFoundInfoSettings {
            get {
                return ResourceManager.GetString("LanguageNotFoundInfoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        internal static string Tab1Title {
            get {
                return ResourceManager.GetString("Tab1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string Tab2Title {
            get {
                return ResourceManager.GetString("Tab2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Tab3Title {
            get {
                return ResourceManager.GetString("Tab3Title", resourceCulture);
            }
        }
    }
}
